require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - "example/*.rb"
    - "tmp/*"

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false # for pythonic

Naming/PredicateName:
  Enabled: false # for pythonic

Naming/VariableNumber:
  Exclude:
    - "test/**/test_*.rb"

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/Documentation:
  Exclude:
    - "test/**/test_*.rb"

Style/KeywordParametersOrder:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: false
  # EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# I need to write 'return' explicitly sometime
Style/RedundantReturn:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Layout/LineLength:
  Max: 150

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false
