AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Naming/AccessorMethodName:
  Enabled: false # for pythonic

Naming/PredicateName:
  Enabled: false # for pythonic

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enable: false

Layout/LineLength:
  Max: 120
