AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "test/**/test_*.rb"

Metrics/MethodLength:
  Max: 30

Naming/AccessorMethodName:
  Enabled: false # for pythonic

Naming/PredicateName:
  Enabled: false # for pythonic

Naming/VariableNumber:
  Exclude:
    - "test/**/test_*.rb"

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/LineEndConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# I need to write 'return' explicitly sometime
Style/RedundantReturn:
  Enabled: false

Layout/LineLength:
  Max: 120
