AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Naming/AccessorMethodName:
  Enabled: false # for pythonic

Naming/PredicateName:
  Enabled: false # for pythonic

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/LineEndConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Enabled: false

Layout/LineLength:
  Max: 120
