module Raioquic
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides

  module Quic
    class Packet
      class QuicHeader
        attr_accessor is_long_header: bool
        attr_accessor version: Integer?
        attr_accessor packet_type: Integer
        attr_accessor destination_cid: String
        attr_accessor source_cid: String
        attr_accessor token: String
        attr_accessor integrity_tag: String
        attr_accessor rest_length: Integer
      end

      class QuicPreferredAddress
        attr_accessor ipv4_addresses: [String] # TODO:
        attr_accessor ipv6_addresses: [String] # TODO:
        attr_accessor connection_id: String
        attr_accessor stateless_reset_token: String
      end
    end

    class PacketBuilder
      class QuicSentPacket
        attr_accessor epoch: untyped
        attr_accessor in_flight: bool
        attr_accessor is_ack_eliciting: bool
        attr_accessor is_crypto_packet: bool
        attr_accessor packet_number: Integer
        attr_accessor packet_type: Integer
        attr_accessor sent_time: untyped
        attr_accessor sent_bytes: Integer
      end

      class QuicPacketBuilder
        attr_accessor packet_number: Integer
      end
    end
  end
end
